---
- name: Template a file to /var/deploy/grafana
  ansible.builtin.file:
    dest: /var/deploy/grafana
    state: directory
    owner: dokku
    group: dokku
- ansible.builtin.template:
    src: grafana.ini.j2
    dest: /var/deploy/grafana/grafana.ini
    owner: dokku
    group: dokku
- ansible.builtin.template:
    src: grafana_datasource.yaml.j2
    dest: /var/deploy/grafana/grafana_datasource.yaml
    owner: dokku
    group: dokku
- import_tasks: dokku_service.yml
  vars:
    service_name: grafana
    storage_items:
      - grafana-storage:/var/lib/grafana
      - /var/deploy/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /var/deploy/grafana/grafana_datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - /var/deploy/grafana/grafana_datasource.yaml:/etc/grafana/datasources/datasources.yaml
    container_name: grafana/grafana-oss:latest
    port_map: http:80:3000