---
- import_tasks: dokku_service.yml
  vars:
    service_name: influxdb
    storage_items:
      - myInfluxVolume:/var/lib/influxdb2
    container_name: influxdb:latest
    port_map: http:80:8086
    disable_the_checks: true
    docker_config:
      - env_var_name: DOCKER_INFLUXDB_INIT_MODE
        env_var_value: setup
      - env_var_name: DOCKER_INFLUXDB_INIT_USERNAME
        env_var_value: bear
      - env_var_name: DOCKER_INFLUXDB_INIT_PASSWORD
        env_var_value: bear
      - env_var_name: DOCKER_INFLUXDB_INIT_ORG
        env_var_value: bear
      - env_var_name: DOCKER_INFLUXDB_INIT_BUCKET
        env_var_value: bear
      - env_var_name: DOCKER_INFLUXDB_INIT_RETENTION
        env_var_value: 6m
      - env_var_name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
        env_var_value: bear