---
- import_tasks: dokku_service.yml
  vars:
    service_name: node-exporter
    storage_items:
      - /proc:/host/proc:ro
      - /:/rootfs:ro
      - /sys:/host/sys:ro
      - node_exporter:/data
    container_name: prom/node-exporter:latest
    port_map: http:80:9100
    docker_options:
      - --net=host
    docker_config:
      - env_var_name: "DOKKU_DOCKERFILE_START_CMD"
        env_var_value: "--collector.textfile.directory=/data --path.procfs=/host/proc --path.sysfs=/host/sys"
    disable_checks: true