---
- name: Template a file to /var/deploy/prometheus
  ansible.builtin.file:
    dest: /var/deploy/prometheus
    state: directory
    owner: dokku
    group: dokku
- ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /var/deploy/prometheus/prometheus.yml
    owner: dokku
    group: dokku
- import_tasks: dokku_service.yml
  vars:
    service_name: prometheus
    docker_options:
      - --privileged
      - --user=root
    storage_items:
    - prometheus-data:/prometheus
    - /var/deploy/prometheus/prometheus.yml:/etc/grafana/provisioning/datasources/datasources.yml
    - /var/run/docker.sock:/var/run/docker.sock
    container_name: prom/prometheus
    port_map: http:80:9090
    disable_checks: true