---
- ansible.builtin.include_role:
    name:  artis3n.tailscale
  vars:
    tailscale_authkey: "{{ lookup('onepassword', 'Tailscale K8S Provison', field='password') }}"
    tailscale_args: "--hostname=brntgarlic --ssh"
- command: sudo tailscale ip --4
  register: tailscale_ip_cmd
- set_fact:
    tailscale_ip: "{{ tailscale_ip_cmd.stdout }}"