version: '3'
includes:
  infra: ./infra
dotenv:
  - .env
vars:
  GOARCH:
    sh: go env GOARCH
  GOOS:
    sh: go env GOOS
tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
  build:
    vars:
      DIRS:
        sh: |
          git diff --name-only HEAD~1 | awk -F "/*[^/]*/*$" '{ print ($1 == "" ? "." : $1); }' | sort | uniq | grep src/apps
    cmds:
      - for: { var: DIRS }
        cmd: pushd {{ .ITEM }} && task build