dev:
	op run --env-file=".env" -- npm run dev

migrate:
	op run --env-file=".env" -- npx prisma migrate dev --name init

studio:
	op run --env-file=".env" -- npx prisma studio

generate:
	npx prisma generate