version: '3'

vars:
  HOST_STORAGE_ROOT: /var/lib/dokku/data/storage/
  APP_NAME: "{{.APP_NAME}}"
  APP_KIND: "{{if .APP_KIND}}{{.APP_KIND}}{{else}}git{{end}}"
tasks:
  dir: "{{ .USER_WORKING_DIR }}"
  dokku:
    cmds:
      - ssh -t dokku@brntgarlic dokku {{.CLI_ARGS}}
  init:
    cmds:
      - task app:dokku -- apps:exists {{ .APP_NAME }} || task app:dokku -- apps:create {{ .APP_NAME }}
      - task: push_env
      - task app:dokku -- letsencrypt:set {{ .APP_NAME }} email voidfiles@gmail.com
      - task app:dokku -- letsencrypt:active {{ .APP_NAME }} || task app:dokku -- letsencrypt:enable {{ .APP_NAME }} 
      - |
        {{ if .APP_VOLUME }}
          task app:dokku -- storage:ensure-directory {{ .APP_NAME }}
          task app:dokku -- storage:list scrapoxy | grep "/var/lib/dokku/data/storage/scrapoxy" || \
            task app:dokku -- storage:mount {{ .APP_NAME }} {{.HOST_STORAGE_ROOT}}{{ .APP_NAME }}:/etc/scrapoxy
        {{ end }}
      - task: build_{{.APP_KIND}}
      - task: deploy_{{.APP_KIND}}
  deploy:
    cmds:
      - task: deploy_{{.APP_KIND}}
  deploy_from_image:
    cmds:
      - task app:dokku -- ps:report {{ .APP_NAME }} --deployed || task app:dokku -- git:from-image {{ .APP_NAME }} {{ .FROM_IMAGE }}:latest
  deploy_git:
    vars:
      VERSION:
        sh: docker images --no-trunc --quiet ghcr.io/voidfiles/{{ .APP_NAME }}:latest
    cmds:
      - |
        docker image save ghcr.io/voidfiles/{{ .APP_NAME }}:latest | \
          pv | \
          ssh -t dokku@brntgarlic dokku git:load-image {{ .APP_NAME }} ghcr.io/voidfiles/{{ .APP_NAME }}@{{ .VERSION }}
  build:
    cmds:
      - task: build_{{.APP_KIND}}
  build_from_image:
    cmds:
      - echo "Not required"
  build_git:
      - |
        pack build ghcr.io/voidfiles/{{ .APP_NAME }}:latest \
          --builder paketobuildpacks/builder-jammy-base \
          --cache-image ghcr.io/voidfiles/{{ .APP_NAME }}-cache:latest \
          --publish
  push_env:
    vars:
      ENV_VARS:
        sh: cat env
      PARSED_VARS: '{{ splitList "\n" .ENV_VARS | join " " }}'
    cmds:
      - task app:dokku -- config:set {{ .APP_NAME }} {{.PARSED_VARS}}
  debug:
    cmds:
      - env
      - echo "{{spew .APP_NAME}}"
      - echo "{{spew .APP_KIND}}"
  logs:
    cmds:
      - task app:dokku -- logs {{.APP_NAME}}
  ports:
    cmds:
      - task app:dokku -- ports:list {{.APP_NAME}}