version: '3'
tasks:
  setup:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - poetry install
      - pipenv run ansible --version
      - pipenv run ansible-galaxy install -r requirements.yml --force
  bootstap_beast:
    dir: "{{.TASKFILE_DIR}}/ansible"
    cmds:
      - poetry run ansible-playbook -i inventory/hetzner --user root playbooks/bootstrap_anisible.yml
  provision_beast:
    dir: "{{.TASKFILE_DIR}}/ansible"
    cmds:
      - poetry run run ansible-playbook -i inventory/beast playbooks/k3s.yml
  fetch_k8s_auth:
      dir: "{{.TASKFILE_DIR}}"
      cmds:
        - scp root@brntgarlic:/etc/rancher/k3s/k3s.yaml {{.TASKFILE_DIR}}/.kubeconfig