- hosts: beast
  become: true
  vars:
    local_ansible_become_pass: "{{ lookup('onepassword', 'local_ansible_become_pass', errors='warn') | d(omit) }}"
    aws_access_key: "{{ lookup('onepassword', 'AWS Access Key', field='access key id', errors='warn') | d(omit) }}"
    aws_secret_access_key: "{{ lookup('onepassword', 'AWS Access Key', field='secret access key', errors='warn') | d(omit) }}"
  tasks:
    - name: Install tailscale
      import_tasks: ../tasks/tailscale.yml
      tags:
        - tailscale
    - name: run k3s
      import_role:
        name: xanmanning.k3s
      vars:
        k3s_release_version: "{{ lookup('ansible.builtin.env', 'K3S_VERSION') }}"
        k3s_become: true
        k3s_build_cluster: false
        k3s_server:
          cluster-domain: "{{ domain_name }}"
          bind-address: "{{ tailscale_ip }}"
    - name: Specifying a destination path
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ../root_k3s.yaml
        flat: true
    - name: Install helm if not exists
      unarchive:
        src: https://get.helm.sh/helm-v3.13.1-linux-arm64.tar.gz
        dest: /usr/local/bin
        extra_opts: "--strip-components=1"
        owner: root
        group: root
        mode: 0755
        remote_src: true
      args:
        creates: /usr/local/bin/helm
    - name: Template a file to /etc/file.conf
      ansible.builtin.template:
        src: /mytemplates/foo.j2
        dest: /var/lib/rancher/k3s/server/manifests/tailnet-operator.yaml
    - name: Install tailscale operator
      ansible.builtin.fetch:
        src: ../tasks/templates/tailscale-operator.yaml.j2
        dest: /var/lib/rancher/k3s/server/manifests/tailnet-operator.yaml
      vars:
        oauth_client_id: "{{ lookup('onepassword', 'tailscale:k8s-operator:oauth-client', field='username', errors='warn') | d(omit) }}"
        oauth_client_secret: "{{ lookup('onepassword', 'tailscale:k8s-operator:oauth-client', field='password', errors='warn') | d(omit) }}"