on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup kpaas
        working-directory: ./infra/kpaas
        run: poetry install
      - name: Install kpaas globally
        working-directory: ./infra/kpaas
        run: pip install .
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
